version: "3.7"

volumes:
  grafana-storage:

networks:
  pizza-network:
    name: pizza-network

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - pizza-network
    environment:
      - POSTGRES_DB=pizza_store_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped

  pizza-viewer:
    image: pizza-viewer
    ports:
      - "8100:8100"
    networks:
      - pizza-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      ZIPKIN: http://zipkin:9411/
      RABBITMQ: rabbitmq
      ZIPKIN-SENDER: rabbit
    restart: unless-stopped

  pizza-cart:
    image: pizza-cart
    ports:
      - "8200:8200"
    networks:
      - pizza-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      ZIPKIN: http://zipkin:9411/
      RABBITMQ: rabbitmq
      ZIPKIN-SENDER: rabbit
    restart: unless-stopped

  pizza-builder:
    image: pizza-builder
    ports:
        - "8000:8000"
    networks:
        - pizza-network
    depends_on:
        - naming-server
        - rabbitmq
    environment:
        ZIPKIN: http://zipkin:9411/
        RABBITMQ: rabbitmq
        ZIPKIN-SENDER: rabbit
    restart: unless-stopped

  naming-server:
    image: naming-server
    ports:
      - "8761:8761"
    networks:
      - pizza-network
    restart: unless-stopped

  api-gateway:
    image: api-gateway
    ports:
      - "8765:8765"
    networks:
      - pizza-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      ZIPKIN: http://zipkin:9411/
      RABBITMQ: rabbitmq
      ZIPKIN-SENDER: rabbit
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    depends_on:
      - rabbitmq
    networks:
      - pizza-network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - pizza-network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - pizza-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - pizza-network
    restart: unless-stopped