CREATE TABLE orders
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE pizza_presets
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              VARCHAR(255),
    pizzas_form       VARCHAR(255),
    has_cheese_boards BOOLEAN,
    default_pizza     BOOLEAN,
    CONSTRAINT pk_pizza_presets PRIMARY KEY (id)
);

CREATE TABLE ingredients
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    type        VARCHAR(255),
    price       DOUBLE PRECISION,
    CONSTRAINT pk_ingredients PRIMARY KEY (id)
);

CREATE TABLE pizza_ingredients
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pizza_id INTEGER NOT NULL,
    ingredient_id INTEGER NOT NULL
);

CREATE TABLE orders_pizzas
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id INTEGER NOT NULL,
    pizza_id INTEGER NOT NULL
);